WIP packaging for Agimus
nim65s/robotpkg-wip pull request #2
Opened 2020-08-26 11:39 UTC by longhathuc

Added packages of agimus to wip, built on ferrum's environment
- agimus
- agimus-hpp
- agimus-sot
- agimus-vision
- agimus-demos
- agimus_sot_msgs

2020-09-08 12:31 UTC, nim65s requested changes

2020-09-08 12:31 UTC, nim65s commented on Makefile
> +#SUBDIR+=	infuse-asn1-conversions
Please don't comment the packages you are not using: they will be used on the buildfarm

2020-09-08 12:31 UTC, nim65s commented on agimus-demos/Makefile
> +MASTER_SITE_AGIMUS=     https://github.com/agimus/
No need for this: we already have `MASTER_SITE_GITHUB`

2020-09-08 12:31 UTC, nim65s commented on agimus-demos/Makefile
> +DOWNLOAD_LOC=   releases/download
No need for this: we usually put:
```
MASTER_SITES?=    ${MASTER_SITE_GITHUB:=${ORG}/${NAME}}/releases/download/v${VERSION}/
```

2020-09-08 12:31 UTC, nim65s commented on agimus-demos/Makefile
> +MASTER_REPOSITORY=	${MASTER_REPOSITORY_GITHUB}${ORG}/${NAME}/${DOWNLOAD_LOC}/v${VERSION}
`MASTER_REPOSITORY` should point to a .git tree: it is used for `make checkout`. Here, you can use:
```
MASTER_REPOSITORY?=	${MASTER_REPOSITORY_GITHUB}${ORG}/${NAME}.git
```

2020-09-08 12:31 UTC, nim65s commented on agimus-demos/Makefile
> +LICENSE=		BSD-2-Clause
In this field, you can only put files that are in the `licenses` directory of the main robotpkg repository. Here, you need `2-clause-bsd`

2020-09-08 12:31 UTC, nim65s commented on agimus-demos/Makefile
> +CMAKE_ARGS+=    -DPYTHON_STANDARD_LAYOUT=ON
I think I created this `PYTHON_STANDARD_LAYOUT` in the jrl-cmakemodule, but it doesn't look like agimus-sot is using that module. Why do you need this arg ?

2020-09-08 12:31 UTC, nim65s commented on agimus-hpp/Makefile
> +MASTER_REPOSITORY=	${MASTER_REPOSITORY_GITHUB}${ORG}/${NAME}/${DOWNLOAD_LOC}/v${VERSION}
Same here

2020-09-08 12:31 UTC, nim65s commented on agimus-hpp/Makefile
> +CMAKE_ARGS+=    -DPYTHON_STANDARD_LAYOUT=ON
This agimus-hpp package uses the jrl-cmakemodule. Therefore, you can use:
```
include ../../devel/jrl-cmakemodules/Makefile.common
```
to setup everything you need: this `-DPYTHON_STANDARD_LAYOUT=ON` is automatically added there, among other features

2020-09-08 12:31 UTC, nim65s commented on agimus-sot/depend.mk
> +	'lib/lib/libagimus_sot.so'
`lib/lib/` ? This looks like a typo

2020-09-08 12:31 UTC, nim65s commented on agimus-vision/Makefile
> +MASTER_REPOSITORY=	${MASTER_REPOSITORY_GITHUB}${ORG}/${NAME}/${DOWNLOAD_LOC}/v${VERSION}
same here

2020-09-08 12:31 UTC, nim65s commented on sysdep/pal-distro.mk
> +     ifeq (palferrum,${PALDISTRO})
I don't think you should remove anything for erbium

2020-09-10 08:44 UTC, longhathuc commented
I have modified the files as your suggestions

2020-09-10 08:46 UTC, longhathuc commented
on robotpkg.conf, I have added these lines

PREFER.py-prf-ros-controllers = robotpkg
PREFER.py-prf-ros-control = robotpkg
PREFER.ros-four-wheel-steering-msgs = robotpkg
PREFER.ros-urdf-geometry-parser = robotpkg
PREFER.ros-actionlib = robotpkg
PREFER.ros-class-loader = robotpkg
PREFER.ros-cmake-modules = robotpkg
PREFER.ros-comm = robotpkg
PREFER.ros-common-msgs = robotpkg
PREFER.ros-genmsg = robotpkg
PREFER.ros-genpy = robotpkg
PREFER.ros-message-generation = robotpkg
PREFER.ros-message-runtime = robotpkg
PREFER.ros-pluginlib = robotpkg
PREFER.ros-ros = robotpkg
PREFER.ros-std-msgs = robotpkg
PREFER.ros-urdf = robotpkg
PREFER.ros-roscpp-core = robotpkg
PREFER.ros-rospack = robotpkg
PREFER.prf-teleop-tools = robotpkg
PREFER.play-motion = system
PREFER.prf-teleop-tools = system
PREFER.pal-gripper = robotpkg
PREFER.ros-orocos-kinematics-dynamics = robotpkg
PREFER.ros-vision-opencv = robotpkg

2020-09-10 12:25 UTC, nim65s requested changes
Thanks, that's better :)
We still have a few tiny details.

2020-09-10 12:25 UTC, nim65s commented on Makefile
> -SUBDIR+=	hrp2-dev
This still shouldn't be removed. Nothing should be removed or commented in this file.

2020-09-10 12:25 UTC, nim65s commented on agimus_sot_msgs/Makefile
> +include ../../devel/jrl-cmakemodules/Makefile.common
Could you put this as the first include ? I'm not sure, but I think this defines important constants for the other includes.

2020-09-10 12:25 UTC, nim65s commented on play-motion/Makefile
> +ifeq (,$(filter 18.04%,${OS_VERSION}))
I don't understand this addition

2020-09-10 12:40 UTC, longhathuc commented
I have modified the files as your suggestions

2020-09-10 13:17 UTC, merged